# Generated by Django 3.2.9 on 2021-11-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField()),
                ('post_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.post')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.voter')),
            ],
        ),
    ]
