# Generated by Django 3.2.8 on 2021-11-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='dept',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='dob',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Manage_Post',
            fields=[
                ('manage_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ec', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.election_coordinator')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.post')),
            ],
        ),
        migrations.CreateModel(
            name='Manage_Candidate',
            fields=[
                ('manage_candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.candidate')),
                ('ec', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.election_coordinator')),
            ],
        ),
    ]
