# Generated by Django 3.2.8 on 2021-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20211130_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Post',
            fields=[
                ('manage_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election_coordinator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.post')),
            ],
        ),
        migrations.CreateModel(
            name='Manage_Candidate',
            fields=[
                ('manage_candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.candidate')),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election_coordinator')),
            ],
        ),
    ]
