# Generated by Django 3.2.8 on 2021-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_election_cordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='password',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='otp',
        ),
        migrations.AddField(
            model_name='voter',
            name='password',
            field=models.CharField(default=12345678, max_length=30),
            preserve_default=False,
        ),
    ]
