# Generated by Django 3.2.8 on 2021-10-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211029_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Election_Cordinator',
            new_name='Election_Coordinator',
        ),
    ]
