# Generated by Django 3.2.8 on 2021-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_election_cordinator_election_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election_coordinator',
            name='id',
        ),
        migrations.AlterField(
            model_name='election_coordinator',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='rollno',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
