# Generated by Django 3.2.8 on 2021-10-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211030_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='manifetso',
            new_name='manifesto',
        ),
    ]
